[server]
headless = true

[theme]
base = "light"
primaryColor = "#1A73E8"        # Google Blue
backgroundColor = "#FFFFFF"     # Pure White
secondaryBackgroundColor = "#F8F9FA" # Google Light Grey (for sidebar/inputs)
textColor = "#202124"           # Google Dark Grey
font = "sans serif"

[client]
toolbarMode = "minimal"